export const GET_ALL_FLAVORS = 'GET_ALL_FLAVORS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const GET_CREDITCARD_INFO = 'GET_CREDITCARD_INFO';
